// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"distributor/core/http/rpc/claim/ent/distributororder"
	"distributor/core/http/rpc/claim/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DistributorOrderDelete is the builder for deleting a DistributorOrder entity.
type DistributorOrderDelete struct {
	config
	hooks    []Hook
	mutation *DistributorOrderMutation
}

// Where appends a list predicates to the DistributorOrderDelete builder.
func (dod *DistributorOrderDelete) Where(ps ...predicate.DistributorOrder) *DistributorOrderDelete {
	dod.mutation.Where(ps...)
	return dod
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dod *DistributorOrderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dod.sqlExec, dod.mutation, dod.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dod *DistributorOrderDelete) ExecX(ctx context.Context) int {
	n, err := dod.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dod *DistributorOrderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(distributororder.Table, sqlgraph.NewFieldSpec(distributororder.FieldID, field.TypeInt))
	if ps := dod.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dod.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dod.mutation.done = true
	return affected, err
}

// DistributorOrderDeleteOne is the builder for deleting a single DistributorOrder entity.
type DistributorOrderDeleteOne struct {
	dod *DistributorOrderDelete
}

// Where appends a list predicates to the DistributorOrderDelete builder.
func (dodo *DistributorOrderDeleteOne) Where(ps ...predicate.DistributorOrder) *DistributorOrderDeleteOne {
	dodo.dod.mutation.Where(ps...)
	return dodo
}

// Exec executes the deletion query.
func (dodo *DistributorOrderDeleteOne) Exec(ctx context.Context) error {
	n, err := dodo.dod.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{distributororder.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dodo *DistributorOrderDeleteOne) ExecX(ctx context.Context) {
	if err := dodo.Exec(ctx); err != nil {
		panic(err)
	}
}
