// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"distributor/core/http/restapi/claim/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/claim/getProof",
				Handler: ClaimHandler(serverCtx),
			},
		},
	)
}
