// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DistributorOrdersColumns holds the columns for the "distributor_orders" table.
	DistributorOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "order_id", Type: field.TypeUint32},
		{Name: "batch_id", Type: field.TypeString},
		{Name: "project_id", Type: field.TypeString},
		{Name: "account", Type: field.TypeString},
		{Name: "amount", Type: field.TypeInt, SchemaType: map[string]string{"postgres": "numeric(78, 0)"}},
		{Name: "index", Type: field.TypeInt},
		{Name: "create_at", Type: field.TypeTime},
		{Name: "p_task_id", Type: field.TypeString},
		{Name: "proof", Type: field.TypeJSON},
	}
	// DistributorOrdersTable holds the schema information for the "distributor_orders" table.
	DistributorOrdersTable = &schema.Table{
		Name:       "distributor_orders",
		Columns:    DistributorOrdersColumns,
		PrimaryKey: []*schema.Column{DistributorOrdersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DistributorOrdersTable,
	}
)

func init() {
}
