// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DistributorOrder is the predicate function for distributororder builders.
type DistributorOrder func(*sql.Selector)
