// Code generated by goctl. DO NOT EDIT!
// Source: claim.proto

package server

import (
	"context"

	"distributor/core/http/rpc/claim/internal/logic"
	"distributor/core/http/rpc/claim/internal/svc"
	"distributor/core/http/rpc/claim/types/claim"
)

type ClaimServer struct {
	svcCtx *svc.ServiceContext
	claim.UnimplementedClaimServer
}

func NewClaimServer(svcCtx *svc.ServiceContext) *ClaimServer {
	return &ClaimServer{
		svcCtx: svcCtx,
	}
}

func (s *ClaimServer) GetProof(ctx context.Context, in *claim.ProofRequest) (*claim.ProofResponse, error) {
	l := logic.NewGetProofLogic(ctx, s.svcCtx)
	return l.GetProof(in)
}
